
package ma.mehdi.Client.proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankService", targetNamespace = "http://Service.mehdi.ma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @param amount
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convert", targetNamespace = "http://Service.mehdi.ma/", className = "ma.mehdi.Client.proxy.Convert")
    @ResponseWrapper(localName = "convertResponse", targetNamespace = "http://Service.mehdi.ma/", className = "ma.mehdi.Client.proxy.ConvertResponse")
    @Action(input = "http://Service.mehdi.ma/BankService/convertRequest", output = "http://Service.mehdi.ma/BankService/convertResponse")
    public double convert(
        @WebParam(name = "amount", targetNamespace = "")
        double amount);

    /**
     * 
     * @return
     *     returns java.util.List<ma.mehdi.Client.proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listComptes", targetNamespace = "http://Service.mehdi.ma/", className = "ma.mehdi.Client.proxy.ListComptes")
    @ResponseWrapper(localName = "listComptesResponse", targetNamespace = "http://Service.mehdi.ma/", className = "ma.mehdi.Client.proxy.ListComptesResponse")
    @Action(input = "http://Service.mehdi.ma/BankService/listComptesRequest", output = "http://Service.mehdi.ma/BankService/listComptesResponse")
    public List<Compte> listComptes();

    /**
     * 
     * @param arg0
     * @return
     *     returns ma.mehdi.Client.proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://Service.mehdi.ma/", className = "ma.mehdi.Client.proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://Service.mehdi.ma/", className = "ma.mehdi.Client.proxy.GetCompteResponse")
    @Action(input = "http://Service.mehdi.ma/BankService/getCompteRequest", output = "http://Service.mehdi.ma/BankService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
